export type Difficulty = "入門" | "初級" | "中級" | "上級";

export type CourseType = "コース" | "学習パス";

export type CourseTag = "e-learning" | "training";

export type CourseDelivery = "self" | "live";

export type MaterialType = "video" | "pdf" | "slide" | "quiz";

export interface Course {
  id: number;
  title: string;
  learners: number;
  type: CourseType;
  delivery: CourseDelivery;
  difficulty: Difficulty;
  duration: string;
  progress: { completed: number; total: number };
  tags: CourseTag[];
  badgeId?: number;
  category: string;
  materialIds?: number[];
}

export interface Badge {
  id: number;
  name: string;
  description: string;
  color: string;
  icon: string;
  courseIds: number[];
  issued: number;
  expires?: string;
}

export interface Material {
  id: number;
  title: string;
  type: MaterialType;
  size: string;
  duration?: string;
  pages?: number;
  createdAt: string;
  updatedAt: string;
  thumbnail: string;
  courseIds: number[];
}

export const MOCK_COURSES: Course[] = [
  {
    id: 1,
    title: "Next.js アプリ開発入門",
    learners: 12,
    type: "コース",
    delivery: "self",
    difficulty: "入門",
    duration: "2時間 15分",
    progress: { completed: 8, total: 12 },
    tags: ["e-learning"],
    category: "フロントエンド",
    materialIds: [101, 102],
  },
  {
    id: 2,
    title: "TypeScript 基礎",
    learners: 20,
    type: "コース",
    delivery: "self",
    difficulty: "初級",
    duration: "4時間",
    progress: { completed: 15, total: 20 },
    tags: ["e-learning", "training"],
    category: "プログラミング",
    materialIds: [102, 103],
  },
  {
    id: 3,
    title: "ChatGPT 基礎講座 知識編",
    learners: 4,
    type: "コース",
    delivery: "self",
    difficulty: "初級",
    duration: "3時間 2分",
    progress: { completed: 4, total: 4 },
    tags: ["e-learning", "training"],
    badgeId: 1,
    category: "AI/ML",
    materialIds: [101, 102],
  },
  {
    id: 4,
    title: "Google AI Explorer パス",
    learners: 7,
    type: "学習パス",
    delivery: "self",
    difficulty: "初級",
    duration: "8時間",
    progress: { completed: 3, total: 7 },
    tags: ["e-learning"],
    badgeId: 2,
    category: "AI/ML",
    materialIds: [104, 105],
  },
  {
    id: 5,
    title: "データサイエンス入門",
    learners: 9,
    type: "コース",
    delivery: "live",
    difficulty: "中級",
    duration: "6時間",
    progress: { completed: 5, total: 9 },
    tags: ["training"],
    badgeId: 3,
    category: "データ",
    materialIds: [106, 107],
  },
  {
    id: 6,
    title: "JavaScript モダン開発",
    learners: 18,
    type: "コース",
    delivery: "self",
    difficulty: "中級",
    duration: "5時間 30分",
    progress: { completed: 10, total: 18 },
    tags: ["e-learning"],
    badgeId: 4,
    category: "フロントエンド",
    materialIds: [108],
  },
  {
    id: 7,
    title: "DX 推進リーダー養成",
    learners: 6,
    type: "学習パス",
    delivery: "live",
    difficulty: "上級",
    duration: "12時間",
    progress: { completed: 2, total: 6 },
    tags: ["training"],
    badgeId: 5,
    category: "ビジネス",
    materialIds: [109, 110],
  },
  {
    id: 8,
    title: "React Hooks 実践",
    learners: 14,
    type: "コース",
    delivery: "self",
    difficulty: "中級",
    duration: "3時間 45分",
    progress: { completed: 14, total: 14 },
    tags: ["e-learning", "training"],
    category: "フロントエンド",
    materialIds: [101, 108],
  },
  {
    id: 9,
    title: "Python 基礎",
    learners: 25,
    type: "コース",
    delivery: "self",
    difficulty: "入門",
    duration: "4時間 20分",
    progress: { completed: 20, total: 25 },
    tags: ["e-learning"],
    category: "プログラミング",
    materialIds: [103, 106],
  },
  {
    id: 10,
    title: "API 設計入門",
    learners: 11,
    type: "コース",
    delivery: "self",
    difficulty: "初級",
    duration: "2時間 50分",
    progress: { completed: 6, total: 11 },
    tags: ["e-learning"],
    category: "バックエンド",
    materialIds: [102],
  },
  {
    id: 11,
    title: "クラウド基礎 AWS",
    learners: 8,
    type: "コース",
    delivery: "live",
    difficulty: "初級",
    duration: "6時間",
    progress: { completed: 4, total: 8 },
    tags: ["training"],
    category: "インフラ",
    materialIds: [104],
  },
  {
    id: 12,
    title: "SQL 入門",
    learners: 16,
    type: "コース",
    delivery: "self",
    difficulty: "入門",
    duration: "2時間",
    progress: { completed: 12, total: 16 },
    tags: ["e-learning"],
    category: "データ",
    materialIds: [107],
  },
  {
    id: 13,
    title: "Git ワークフロー",
    learners: 22,
    type: "コース",
    delivery: "self",
    difficulty: "入門",
    duration: "1時間 30分",
    progress: { completed: 18, total: 22 },
    tags: ["e-learning", "training"],
    category: "ツール",
    materialIds: [110],
  },
  {
    id: 14,
    title: "セキュリティ基礎",
    learners: 10,
    type: "コース",
    delivery: "self",
    difficulty: "初級",
    duration: "3時間",
    progress: { completed: 7, total: 10 },
    tags: ["e-learning"],
    category: "セキュリティ",
    materialIds: [101, 103],
  },
  {
    id: 15,
    title: "アジャイル開発入門",
    learners: 15,
    type: "学習パス",
    delivery: "live",
    difficulty: "初級",
    duration: "5時間",
    progress: { completed: 9, total: 15 },
    tags: ["training"],
    category: "ビジネス",
    materialIds: [109],
  },
  {
    id: 16,
    title: "Tailwind CSS 実践",
    learners: 13,
    type: "コース",
    delivery: "self",
    difficulty: "初級",
    duration: "2時間 40分",
    progress: { completed: 11, total: 13 },
    tags: ["e-learning"],
    category: "フロントエンド",
    materialIds: [108],
  },
  {
    id: 17,
    title: "Docker 入門",
    learners: 9,
    type: "コース",
    delivery: "self",
    difficulty: "初級",
    duration: "3時間 15分",
    progress: { completed: 5, total: 9 },
    tags: ["e-learning"],
    category: "インフラ",
    materialIds: [104, 110],
  },
  {
    id: 18,
    title: "GraphQL 基礎",
    learners: 7,
    type: "コース",
    delivery: "self",
    difficulty: "中級",
    duration: "4時間",
    progress: { completed: 3, total: 7 },
    tags: ["e-learning"],
    category: "バックエンド",
    materialIds: [102, 106],
  },
  {
    id: 19,
    title: "機械学習入門",
    learners: 6,
    type: "学習パス",
    delivery: "self",
    difficulty: "上級",
    duration: "10時間",
    progress: { completed: 2, total: 6 },
    tags: ["e-learning", "training"],
    badgeId: 3,
    category: "AI/ML",
    materialIds: [106, 107],
  },
  {
    id: 20,
    title: "プレゼン技法",
    learners: 19,
    type: "コース",
    delivery: "live",
    difficulty: "入門",
    duration: "2時間",
    progress: { completed: 14, total: 19 },
    tags: ["training"],
    category: "ビジネス",
    materialIds: [109],
  },
  {
    id: 21,
    title: "Node.js バックエンド",
    learners: 8,
    type: "コース",
    delivery: "self",
    difficulty: "中級",
    duration: "5時間 45分",
    progress: { completed: 6, total: 8 },
    tags: ["e-learning"],
    category: "バックエンド",
    materialIds: [108, 110],
  },
];

export const MOCK_BADGES: Badge[] = [
  {
    id: 1,
    name: "ChatGPT マスター",
    description: "ChatGPT基礎講座を修了した証明バッジ",
    color: "#6366f1",
    icon: "🤖",
    courseIds: [3],
    issued: 4,
  },
  {
    id: 2,
    name: "Google AI Explorer",
    description: "Google AI 探索パスを修了した証明",
    color: "#8b5cf6",
    icon: "🔮",
    courseIds: [4],
    issued: 3,
  },
  {
    id: 3,
    name: "データサイエンティスト初級",
    description: "データサイエンス入門コース修了",
    color: "#0ea5e9",
    icon: "📊",
    courseIds: [5, 19],
    issued: 7,
  },
  {
    id: 4,
    name: "JavaScript Developer",
    description: "JavaScript モダン開発コース修了",
    color: "#eab308",
    icon: "⚡",
    courseIds: [6],
    issued: 10,
  },
  {
    id: 5,
    name: "DX推進リーダー",
    description: "DX推進リーダー養成パス修了",
    color: "#ec4899",
    icon: "🎯",
    courseIds: [7],
    issued: 2,
    expires: "2025-12-31",
  },
];

export const MOCK_MATERIALS: Material[] = [
  {
    id: 101,
    title: "ChatGPT 基礎 — 導入動画",
    type: "video",
    size: "248 MB",
    duration: "28分",
    createdAt: "2024-04-01",
    updatedAt: "2024-06-10",
    thumbnail: "🎬",
    courseIds: [3, 8, 14],
  },
  {
    id: 102,
    title: "TypeScript 型システム",
    type: "slide",
    size: "12 MB",
    pages: 45,
    createdAt: "2024-03-15",
    updatedAt: "2024-05-20",
    thumbnail: "📑",
    courseIds: [2, 3, 10, 18],
  },
  {
    id: 103,
    title: "プログラミング基礎クイズ",
    type: "quiz",
    size: "1 MB",
    createdAt: "2024-02-01",
    updatedAt: "2024-04-15",
    thumbnail: "❓",
    courseIds: [2, 9, 14],
  },
  {
    id: 104,
    title: "クラウド概論動画",
    type: "video",
    size: "180 MB",
    duration: "35分",
    createdAt: "2024-05-10",
    updatedAt: "2024-06-01",
    thumbnail: "🎬",
    courseIds: [4, 11, 17],
  },
  {
    id: 105,
    title: "AI ツール比較 PDF",
    type: "pdf",
    size: "8 MB",
    pages: 22,
    createdAt: "2024-04-20",
    updatedAt: "2024-05-30",
    thumbnail: "📄",
    courseIds: [4],
  },
  {
    id: 106,
    title: "データ分析入門スライド",
    type: "slide",
    size: "25 MB",
    pages: 60,
    createdAt: "2024-03-01",
    updatedAt: "2024-06-05",
    thumbnail: "📑",
    courseIds: [5, 9, 18, 19],
  },
  {
    id: 107,
    title: "SQL ハンズオン",
    type: "video",
    size: "95 MB",
    duration: "45分",
    createdAt: "2024-02-20",
    updatedAt: "2024-05-10",
    thumbnail: "🎬",
    courseIds: [5, 12, 19],
  },
  {
    id: 108,
    title: "React 実践演習",
    type: "video",
    size: "320 MB",
    duration: "1時間 10分",
    createdAt: "2024-04-15",
    updatedAt: "2024-06-12",
    thumbnail: "🎬",
    courseIds: [1, 6, 8, 16, 21],
  },
  {
    id: 109,
    title: "DX 戦略ケーススタディ",
    type: "pdf",
    size: "15 MB",
    pages: 38,
    createdAt: "2024-05-01",
    updatedAt: "2024-06-08",
    thumbnail: "📄",
    courseIds: [7, 15, 20],
  },
  {
    id: 110,
    title: "Git ブランチ戦略",
    type: "slide",
    size: "6 MB",
    pages: 28,
    createdAt: "2024-01-10",
    updatedAt: "2024-04-25",
    thumbnail: "📑",
    courseIds: [7, 13, 17, 21],
  },
  {
    id: 111,
    title: "Next.js ルーティング",
    type: "video",
    size: "88 MB",
    duration: "22分",
    createdAt: "2024-05-20",
    updatedAt: "2024-06-11",
    thumbnail: "🎬",
    courseIds: [1],
  },
  {
    id: 112,
    title: "セキュリティクイズ",
    type: "quiz",
    size: "2 MB",
    createdAt: "2024-04-05",
    updatedAt: "2024-05-18",
    thumbnail: "❓",
    courseIds: [14],
  },
];
